Set Up Git Hub Actions
Hyp-ed/hyped-2021 pull request #24
Opened 2021-01-15 18:59 UTC by pmorande27

## Description
Set Up Git Hub Actions for the repository.

2021-01-15 19:54 UTC, MiltFra requested changes
I would have it run on all branches so we can catch bugs early. Even though that is already done with the GitHooks? I don't know, but it's not hard to do and we don't have too much traffic so it should not be an issue. 

To do that, just set

```
on: [push, pull_request]
```

and it will be applied to all branches.

2021-01-16 10:12 UTC, MiltFra commented
Also: fixes #22

2021-01-18 19:06 UTC, DonaldJennings commented
Seems good to me! Although im not very familiar with Github Actions haha

2021-01-18 19:07 UTC, DonaldJennings approved these changes

2021-01-18 19:13 UTC, MiltFra approved these changes

2021-01-18 19:14 UTC, merged