Added messages.hpp and messages.cpp for message refactoring
Hyp-ed/hyped-2021 pull request #28
Opened 2021-01-25 14:35 UTC by efe-ozbatur

## Description
Added messages.hpp and messages.cpp for message refactoring

## Changes
- messages.cpp doesn't have any code
- messages.hpp includes the messages and transitions.cpp uses the messages from that file

## Additional Info 
- stm variable is also available for easily writing "STM"

2021-01-25 14:42 UTC, mifrandir commented on src/state_machine/messages.hpp
> +const char *m_critical_navigation = critical_failure_navigation.c_str();
Only the declaration, i.e. 
```
std::string stop_command;
```
belongs in the header. The actual literal should be in the .cpp file. 

This way the string literal gets redefined every time a .cpp file (implicitly) includes the messages.hpp header and thus the linker cannot be sure which memory location is actually being referred to.

2021-01-25 14:45 UTC, MiltFra commented
Also, the duplication between `std::string` and the C-style strings `char *` seems a bit clunky here. Do we really need the latter? If the logger doesn't support this (which I'd be surprised by), it shouldn't be too difficult to add this feature.

2021-01-25 21:47 UTC, MiltFra commented
This is required because we're stuck on C++11 and inline variables are only available from C++17 onwards...

It ain't too pretty, but I think it's fine.

2021-01-25 22:06 UTC, MiltFra approved these changes
It looks fine to me for now, though this is not yet as convenient as I'd llike it to be. (But it will do for testing, so this is fine.)

2021-01-26 15:56 UTC, DonaldJennings approved these changes
Very nice refactoring 👍🏻 Looks good to me :).

2021-01-27 09:23 UTC, MiltFra requested changes
You are missing [this](https://github.com/Hyp-ed/hyped-2021/blob/9b15a590de4e54ab5c4474ddec22f96f37092000/src/state_machine/state.hpp#L81).

2021-01-27 11:00 UTC, MiltFra commented
TL;DR: Don't import what you don't use!

2021-01-27 11:12 UTC, MiltFra approved these changes

2021-01-27 11:12 UTC, merged