[WIP] STM: Implemented sketch of cruising state
Hyp-ed/hyped-2021 pull request #37
Opened 2021-02-08 20:39 UTC by MiltFra

**!!! DO NOT MERGE YET !!!**

This implements a good sketch of how we could implement a cruising state without affecting the current behaviour.

Changes include:
- added Cruising state internally
- added `kCruising` to central data structure
- added maximum_velocity to navigation data

ToDo:
- [ ] all modules need to handle `kCruising`
- [ ] check with tech heads that this is the desired behaviour

2021-02-09 21:56 UTC, MiltFra commented
Here's the corresponding state diagram:

![stm_diagram_v1 1 1](https://user-images.githubusercontent.com/32496059/107433704-9dc5a280-6b21-11eb-8e9f-016fd944c651.png)

2021-02-11 18:13 UTC, DonaldJennings requested changes
Very minor typos. Otherwise looks all good

2021-02-11 18:13 UTC, DonaldJennings commented on src/state_machine/state.hpp
> +MAKE_STATE(Cruising)        // Itermediate phase to not exceed maximum velocity
Typo with intermediate

2021-02-11 18:13 UTC, DonaldJennings commented on src/state_machine/transitions.hpp
> + * @brief    Returns true iff all modulesare ready.
Typo with "modulesare" to "modules are". The meaning is clear from context but just a consistency thing.

2021-03-08 17:37 UTC, Akshath29 approved these changes

2021-03-08 22:37 UTC, MiltFra commented
The only thing we're waiting for at the moment is sensors to add their calibration.

2021-03-11 08:17 UTC, robertasn requested changes

2021-03-11 08:17 UTC, robertasn commented on src/data/data.cpp
>    "Exiting",
Do we still need this one here?

2021-03-11 08:37 UTC, MiltFra commented on src/data/data.cpp
>    "Exiting",
No, good spot

2021-03-15 20:58 UTC, robertasn requested changes
Please resolve conflicts

2021-03-17 17:07 UTC, robertasn requested changes
![image](https://user-images.githubusercontent.com/22636210/111508139-0a047900-8754-11eb-9c49-8500cbb79691.png)

2021-03-17 17:24 UTC, MiltFra commented
> ![image](https://user-images.githubusercontent.com/22636210/111508139-0a047900-8754-11eb-9c49-8500cbb79691.png)

@MrTooOldDriver @Videosquared

2021-03-19 11:46 UTC, robertasn commented
![image](https://user-images.githubusercontent.com/22636210/111775446-6f25af00-88b9-11eb-927b-8004776f7d45.png)
Does not exit NOMINAL_BRAKING state. In addition, CRUISING state is never entered.

2021-03-19 18:02 UTC, Akshath29 approved these changes

2021-03-26 19:16 UTC, robertasn commented
A pull request has been merged into develop, which had unit tests for telemetry. Could you merge in develop and add new tests for the cruising part?

2021-07-06 14:45 UTC, DonaldJennings approved these changes
Looks good to me!

2021-07-28 07:56 UTC, robertasn approved these changes
LGTM

2021-07-28 17:24 UTC, merged