TLM: Create unit tests for status/state converters
Hyp-ed/hyped-2021 pull request #70
Opened 2021-03-22 12:46 UTC by robertasn

## Description
Unit tests for status/state converters have been created

2021-03-22 13:00 UTC, DonaldJennings requested changes
Just a few minor changes to make which centre around the Testing style guide. Make sure all asserts have an appropriate error message in case of failing and that the test names begin with a verb.

2021-03-22 13:00 UTC, DonaldJennings commented on test/src/telemetry/writerConvertStateMachineState.test.cpp
> +  ASSERT_EQ(Writer::convertStateMachineState(State::kIdle), "IDLE");
You should add some error messages at the end of each ASSERT() for the case that the test fails then we can get a meaningful message with it. [Refer to this with Error messages](https://hyp-ed.github.io/styleguide/#Error%20Messages)

2021-03-22 13:00 UTC, DonaldJennings commented on test/src/telemetry/writerConvertStateMachineState.test.cpp
> +struct WriterConvertStateMachineState : public ::testing::Test {
This should have a comment explaining what these tests are. Comments may not be needed for the actual tests but the struct should always have one : )

2021-03-22 13:00 UTC, DonaldJennings commented on test/src/telemetry/writerConvertStateMachineState.test.cpp
> + *    Copyright 2019 HYPED
This should probably be 2021 HYPED.

2021-03-22 13:00 UTC, DonaldJennings commented on test/src/telemetry/writerConvertStateMachineState.test.cpp
> +TEST_F(WriterConvertStateMachineState, calibratingState)
Try make the test names more meaningful . Test names should always begin with a verb such as "handles" or "accepts" to name a few examples. A good one for this case could be "converts" so the name of this particular test could be "convertsCalibratingState"

2021-03-22 13:00 UTC, DonaldJennings commented on test/src/telemetry/writerConvertModuleStatus.test.cpp
> + *    Copyright 2019 HYPED
Same as other comment. This should be 2021 HYPED and the Date and description should be filled out

2021-03-22 13:00 UTC, DonaldJennings commented on test/src/telemetry/writerConvertStateMachineState.test.cpp
> + *    Copyright 2019 HYPED
Date and Description should also be filled out

2021-03-22 13:00 UTC, MiltFra commented
The file names seem a bit off to me. I think we are using snake_case everywhere else.

2021-03-22 13:02 UTC, DonaldJennings commented
@MiltFra yea just noticed that as well the general naming for files should be snake_case

2021-03-22 22:46 UTC, DonaldJennings approved these changes

2021-03-26 18:29 UTC, pmorande27 approved these changes
Seems okay as a starting point for testing :)

2021-03-26 19:14 UTC, merged